// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


function fetchPosts(param) {
  return new Promise((function (resolve, param) {
                setTimeout((function (param) {
                        return resolve(/* :: */[
                                    /* record */[
                                      /* id */1,
                                      /* title */"Post 1"
                                    ],
                                    /* :: */[
                                      /* record */[
                                        /* id */2,
                                        /* title */"Post 2"
                                      ],
                                      /* [] */0
                                    ]
                                  ]);
                      }), 3000);
                return /* () */0;
              }));
}

exports.fetchPosts = fetchPosts;
/* No side effect */
