// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function fetchPosts(param) {
  return new Promise((function (resolve, param) {
                setTimeout((function (param) {
                        return resolve(/* :: */[
                                    {
                                      id: 1,
                                      title: "Post 1"
                                    },
                                    /* :: */[
                                      {
                                        id: 2,
                                        title: "Post 2"
                                      },
                                      /* [] */0
                                    ]
                                  ]);
                      }), 3000);
                return /* () */0;
              }));
}

exports.fetchPosts = fetchPosts;
/* No side effect */
