// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var PostsComponentWithLoader$ReactTemplate = require("./PostsComponentWithLoader.bs.js");

function App(Props) {
  return React.createElement("div", undefined, React.createElement(PostsComponentWithLoader$ReactTemplate.PostsComponentWithLoader[/* make */2], { }));
}

var make = App;

exports.make = make;
/* react Not a pure module */
