// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Counter$ReactTemplate = require("./Counter.bs.js");

function App(Props) {
  return React.createElement("div", undefined, React.createElement(Counter$ReactTemplate.make, { }));
}

var make = App;

exports.make = make;
/* react Not a pure module */
